name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: xcodebuild -scheme DukascopyDecoder test -destination 'platform=macOS' -enableCodeCoverage YES -parallel-testing-enabled YES

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

  test_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: swift test -v
